### PR TITLE
 Convert `version.sh` to Powershell

### LINKED ISSUE #21: Replace version.sh with a native solution
Right now version.sh is used which requires bash. Would be nice if we could get rid of this and replace the functionality with a native solution.

### PR DESCRIPTION
**Pull request by cmconti**
converted bash script to powershell

Fixes #21

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hey, thanks for the PR and sorry for the late response!

I'll try to take care of this in the next days. If you have any other patches, feel free to make a PR.

**Review by XhmikosR — APPROVED** [review]

**Comment by XhmikosR** [comment]
@cmconti do you know why this prints `Powershell 5.1 or later is not installed` on Actions, but doesn't break the build and sets the version variable properly (which is a good thing, though)?

https://github.com/XhmikosR/perfmonbar/runs/5549974640?check_suite_focus=true#step:4:107

**Comment by cmconti** [comment]
It looks like when the dev environment sets up for the x64 build, powershell is being removed from the path.  I can't replicate it locally on my machine where I have VS2022 (17.1) installed.

It works because the x86 build, which runs first, has already set the correct version info

To debug it, I would probably start by modifying the pre-build steps to dump the path before calling the update script to confirm

when I tried it with my fork
https://github.com/cmconti/perfmonbar/runs/5554610248?check_suite_focus=true
you can see the second time path is displayed, it is empty: `PATH=`

**Comment by XhmikosR** [comment]
Thanks for the reply!

Yeah, indeed something is going wrong there. I wonder if it has to do with ilammy/msvc-dev-cmd. I'll try reverting it and see how it goes.

If you have any further tweaks, feel free to make a PR :)

**Pull request merged**
