### PR TITLE
Add possibility to configure decimal subtraction of show value

### LINKED ISSUE #27: Support for "add" and "subtract" operations
I'm trying to read CPU temp, but the counter comes back in Kelvin - whereas I want Celcius. All I need to to is subtract 273.15 from the counter value. Really you would only need to implement an "add" then I can just put in a negative number.

### PR DESCRIPTION
**Pull request by radek-bruha**
I introduced new configuration option `subtract` for `display` tag, because someone wanted to have option subtract some value from counter value. Default value is 0 which means no subtraction at all (like until now).

Fixes #27

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can you switch this to `add` please? Or add `add` too maybe?

**Comment by XhmikosR** [comment]
Feel free to resubmit the PR after taking care of the comment above; I changed master to main and the PR was closed automatically :)

**Comment by ma-zal** [comment]
@radek-bruha I like your idea to add a `subtract` parameter for ability to display temp in °C. Can you, please, to re-send your pull request as @XhmikosR mentioned in the previous post? Thanks a lot! :)

**Comment by radek-bruha** [comment]
Hello, sorry but I cannot. I am using Windows 11 now, which is not allowing this extension anymore and I don't even have needed developer tools.

**Comment by XhmikosR** [comment]
#44

**Pull request closed without merging**
